name:           hsemail
version:        "2"
synopsis:       Parsec parsers for the RFC2822 Internet Message format
author:
  - Peter Simons
  - Ali Abrar
  - Gero Kriependorf
  - Marty Pauley
maintainer:     Peter Simons <simons@cryp.to>
license:        BSD3
license-file:   LICENSE
github:         peti/hsemail
category:       Parsing
stability:      stable
tested-with:    GHC == 7.0.4, GHC > 7.4 && < 8.1
description:    Parsec parsers for the Internet Message format defined in RFC 2821 and 2822.

ghc-options:    -Wall

dependencies:
  - base >= 3 && < 5
  - old-time
  - parsec >= 3.1
  - mtl

library:
  source-dirs: src
  exposed-modules:
    - Text.Parsec.Rfc2234
    - Text.Parsec.Rfc2821
    - Text.Parsec.Rfc2822

tests:
  test-hsemail:
    source-dirs: test
    main: spec.hs
    dependencies:
      - hspec
      - hsemail

  doctest-hsemail:
    source-dirs: test
    main: doctest.hs
    dependencies:
      - doctest
